Repository caicloud/canary-release, pull requests merged in 2018-10, with the labels that each got.

#23 chore(owner): add owner
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#27 feat: clean up proxy when canary release is adopted/deprecated
  controller/controller/canary.go
  controller/controller/retry.go
  controller/controller/status.go
  pkg/api/deepcopy.go
  pkg/util/retry.go
  proxies/nginx/controller/proxy.go
Labels: approved, caicloud-cla: yes, lgtm

#26 fix(nodeport): keep nodePort stable when canary release is created or adopted
  proxies/nginx/controller/proxy.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
